### ISSUE TITLE
Error: Specified Tailwind config file "...\tailwind.js" doesn't exist.

### ISSUE THREAD

**Issue by FeryBris** [JeffreyWay/laravel-mix-tailwind#19]
In Tailwindcss v1.1.2 config file name is tailwind.config.js

https://tailwindcss.com/docs/upgrading-to-v1#3-rename-tailwind-js-to-tailwind-config-js

**Comment by etdte** [comment]
Look here for solution. #8

**Comment by talentedaamer** [comment]
inside your project root where `package.json` and `webpack.mix.js` file is present, run the following command.
`npx tailwind init`

it will generate a file **`tailwind.config.js`**. rename it to **`tailwind.js`** and run `npm run dev `again.

or simply create a file `tailwind.js` and paste the following default config code there.

```
module.exports = {
  theme: {
    extend: {}
  },
  variants: {},
  plugins: []
}

```
run `npm run dev `and it will fix the error.

**Comment by osmanskaya** [comment]
Weird that this still isn't fixed. But thanks @talentedaamer, it worked for me.

**Comment by Wulfheart** [comment]
@Elite40 it should be quite easy to fix.
