### ISSUE TITLE
NPM Newbie - Errors on `npm run dev'

### ISSUE THREAD

**Issue by sergebenard** [JeffreyWay/laravel-mix-tailwind#2]
I am new to NPM.

I get two errors while running `npm run dev`.

The `npm-debug.log` file is attached.

I am unsure what to do. How do I fix this?

[npm-debug.log](https://github.com/JeffreyWay/laravel-mix-tailwind/files/1896716/npm-debug.log)

Thank you very much Jeffrey Way for the great framework, and wonderful tools.

Serge

**Comment by cytRasch** [comment]
Hey @sergebenard,

the log says almost everything you need to fix it.

```
2 info using npm@3.5.2
3 info using node@v6.11.4
```

```23 error Make sure you have the latest version of node.js and npm installed.```

Just update your npm and node by using this to update node via npm:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

and this to update npm itself:
```
sudo npm install -g npm
```

You can check your version with ```node -v``` and ```npm -v```.

Happy Coding!
