### ISSUE TITLE
Tailwind 2.0 compatibility

### ISSUE THREAD

**Issue by gnarhard** [JeffreyWay/laravel-mix-tailwind#29]

**Comment by gnarhard** [comment]
@JeffreyWay I'd be happy to fix this on my own when 2.0 compatibility exists, but I wanted to put this on the radar.

**Comment by hmaesta** [comment]
Hey @GraysonE. Did you manage to make it work?

**Comment by gnarhard** [comment]
> Hey @GraysonE. Did you manage to make it work?

Not yet, but I did get Tailwind to work with Laravel Mix using the compatibility version:
https://tailwindcss.com/docs/guides/laravel

**Comment by gnarhard** [comment]
@hmaesta I think it'll be simpler to patch once Laravel Mix's PostCSS 8 support becomes available.

**Comment by hmaesta** [comment]
@GraysonE Oops... I was paying too much attention to the [PostCSS 7 compatibility build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) page and didn't realize that there was a laravel-mix tutorial 😅

Now I could make it work. Thank you for your help!

**Comment by lbssousa** [comment]
> 
> 
> @hmaesta I think it'll be simpler to patch once Laravel Mix's PostCSS 8 support becomes available.

Laravel Mix v6.0.0 (with PostCSS 8 support) was just released last week.
