### ISSUE TITLE
Using the new `@tailwindcss/jit` compiler

### ISSUE THREAD

**Issue by Yiddishe-Kop** [JeffreyWay/laravel-mix-tailwind#31]
I'm super excited to use the new [`@tailwindcss/jit`](https://github.com/tailwindlabs/tailwindcss-jit) compiler 🤤.
However I haven't had any success using it with this package.

Any ideas?

I'm on Laravel Mix v6 & Postcss 8.2.1

**Comment by florianbouvot** [comment]
It works for me without this plugin and using this config: https://github.com/florianbouvot/laravel-mix-boilerplate/tree/next

**Comment by Yiddishe-Kop** [comment]
[This](https://github.com/tailwindlabs/tailwindcss-jit/issues/24#issuecomment-800590828) fixed it for me.
