### ISSUE TITLE
Requires yarn?

### ISSUE THREAD

**Issue by nvahalik** [JeffreyWay/laravel-mix-tailwind#4]
I followed the instructions and got an error about `yarn` not being available. Does this package require yarn? If it does, can you add that to the README?

**Comment by JeffreyWay** [comment]
If you have a yarn.lock file in your project root, it'll try to use Yarn. Delete that file to use npm.

**Comment by combs** [comment]
@JeffreyWay My project doesn't have a yarn.lock, but I do have yarn installed on my machine, and laravel-mix is trying to use it (thus making a yarn lockfile).
